c_compiler_version:    # [linux]
  - 7.3                # [linux]
cxx_compiler_version:  # [linux]
  - 7.3                # [linux]
python:
  - 3.6
  - 3.7
  - 3.8
pytorch:
  - 1.4
  - 1.5
ccache_method: "mklink"
