c_compiler_version:    # [linux]
  - 7.3                # [linux]
cxx_compiler_version:  # [linux]
  - 7.3                # [linux]
pytorch:
  - 1.8
python:
  - 3.7
  - 3.8
  - 3.9
ccache_method: "mklink"
